### User Signup
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phone": "9876543210",
  "email": "john.doe@example.com",
  "password": "SecurePass123!",
  "gender": "Male",
  "dob": "1995-08-15",
  "profilePic": "https://cdn-icons-png.flaticon.com/512/9131/9131529.png",
  "location_latitude": 28.6139,
  "location_longitude": 77.2090,
  "isGoogleUser": false
}

### User Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePass123!"
}

### Superadmin Signup
POST http://localhost:3000/api/v1/auth/superadmin/signup
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminStrongPass123"
}

### Superadmin Login
POST http://localhost:3000/api/v1/auth/superadmin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminStrongPass123"
}

### Medical Centre Login
POST http://localhost:3000/api/v1/auth/medicalcentre/login
Content-Type: application/json

{
  "email": "clinic@example.com",
  "password": "ClinicSecurePass123"
}

### Add Medical Centre
POST http://localhost:3000/api/v1/medical/addmedicalcentre
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "medicalcentre_name": "Green Valley Hospital",
  "registration_number": "GVH123456",
  "mobile_no": "9998887770",
  "email": "greenvalley@example.com",
  "address_line": "123 Health Street",
  "area": "Sector 15",
  "district": "Lucknow",
  "state": "Uttar Pradesh",
  "pincode": "226010"
}

### Verify Medical Centre
POST http://localhost:3000/api/v1/medical/verifycentres/:medicalCentreId
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "is_verified": true
}

### Fetch all medical centres by superadmin (with token)
POST http://localhost:3000/api/v1/medical/getallmedicalcentres?page=1&limit=10
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

### Get Nearest Medical Centres (within 100 km)
POST http://localhost:3000/api/v1/medical/getnearestmedicalcentres?page=1&limit=10
Authorization: Bearer <your_user_token>
Content-Type: application/json

{
  "latitude": 22.5731358,
  "longitude": 88.4343624,
  "radius": 100
}
