### User Signup
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phone": "9876543210",
  "email": "john.doe@example.com",
  "password": "SecurePass123!",
  "gender": "Male",
  "dob": "1995-08-15",
  "profilePic": "https://cdn-icons-png.flaticon.com/512/9131/9131529.png",
  "location_latitude": 28.6139,
  "location_longitude": 77.2090,
  "isGoogleUser": false
}

### User Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePass123!"
}

### Refresh Access Token
GET http://localhost:3000/api/v1/auth/refresh
# No body needed; refreshToken is sent automatically in the HttpOnly cookie

### Superadmin Signup
POST http://localhost:3000/api/v1/auth/superadmin/signup
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminStrongPass123"
}

### Superadmin Login
POST http://localhost:3000/api/v1/auth/superadmin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminStrongPass123"
}

### Medical Centre Login
POST http://localhost:3000/api/v1/auth/medicalcentre/login
Content-Type: application/json

{
  "email": "clinic@example.com",
  "password": "ClinicSecurePass123"
}

### Add Medical Centre
POST http://localhost:3000/api/v1/medical/addmedicalcentre
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "medicalcentre_name": "Green Valley Hospital",
  "registration_number": "GVH123456",
  "mobile_no": "9998887770",
  "email": "greenvalley@example.com",
  "address_line": "123 Health Street",
  "area": "Sector 15",
  "district": "Lucknow",
  "state": "Uttar Pradesh",
  "pincode": "226010"
}

### Verify Medical Centre
POST http://localhost:3000/api/v1/medical/verifycentres/:medicalCentreId
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "is_verified": true
}

### Fetch all medical centres by superadmin (with token)
POST http://localhost:3000/api/v1/medical/getallmedicalcentres?page=1&limit=10
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

### Get Nearest Medical Centres (within 100 km) USER
POST http://localhost:3000/api/v1/medical/getnearestmedicalcentres?page=1&limit=10&search=anu
Authorization: Bearer <your_user_token>
Content-Type: application/json

{
  "latitude": 22.5731358,
  "longitude": 88.4343624,
  "radius": 100
}

### delete medical centre
POST http://localhost:3000/api/v1/medical/deletemedicalcentre/:id
Authorization: Bearer <your_superadmin_token>

### ADD test to catalouge
POST http://localhost:3000/api/v1/medical/addtesttocatalogue
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "test_name": "Ultrasound Abdomen",
  "type_of_test": "Imaging",
  "components": ["Liver", "Gallbladder", "Pancreas", "Kidneys", "Spleen"]
}

### Add Test to Centre
POST http://localhost:3000/api/v1/medical/tests/assign
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "test_id": "2b2b13aa-c85e-433e-bd3b-1171f33a538d",
  "medicalcentre_id": "MC-1748503434482",
  "price": 450
}


### Get Tests for Medical Centre (with pagination, filter & search) USER
POST http://localhost:3000/api/v1/medical/tests/centre/:medicalcentre_id?page=1&limit=10&type_of_test=Blood&search=liver
Authorization: Bearer <your_user_token>
Content-Type: application/json

# Replace {{medicalcentre_id}} with actual medical centre id


### Get Medical Centre Details with Test Summary
POST http://localhost:3000/api/v1/medical/details/:medicalcentre_id
Authorization: Bearer <your_user_token>


### Get Tests for Medical Centre (with pagination, filter & search) superadmin
POST http://localhost:3000/api/v1/medical/superadmin/tests/centre/:medicalcentre_id?page=1&limit=10&type_of_test=Blood&search=liver
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

# Replace {{medicalcentre_id}} with actual medical centre id


### Get Medical Centre Details with Test Summary superadmin
POST http://localhost:3000/api/v1/medical/superadmin/details/:medicalcentre_id
Authorization: Bearer <your_superadmin_token>



### Combine filters and pagination fetch test catalouge
POST http://localhost:3000/api/v1/medical/tests_catalouge?page=1&limit=10&type_of_test=Imaging&search=ultra
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json