### Send OTP to email
POST http://localhost:3000/api/auth/sendotp
Content-Type: application/json

{
  "email": "user@example.com"
}


### User Signup
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

## non google user

{
  "firstName": "John",
  "lastName": "Doe",
  "phone": "9876543210",
  "email": "john.doe@example.com",
  "password": "securePassword123",
  "gender": "Male",
  "dob": "1995-08-15",
  "profilePic": "https://cdn-icons-png.flaticon.com/512/9131/9131529.png",
  "location_latitude": 22.5726,
  "location_longitude": 88.3639,
  "isGoogleUser": false,
  "otp": "123456"
}
## google user

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@gmail.com",
  "profilePic": "https://lh3.googleusercontent.com/a/default-user.jpg",
  "isGoogleUser": true
}

### User Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePass123!"
}

### Refresh Access Token
GET http://localhost:3000/api/v1/auth/refresh
# No body needed; refreshToken is sent automatically in the HttpOnly cookie

### Superadmin Signup
POST http://localhost:3000/api/v1/auth/superadmin/signup
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminStrongPass123"
}

### Superadmin Login
POST http://localhost:3000/api/v1/auth/superadmin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminStrongPass123"
}

### Medical Centre Login
POST http://localhost:3000/api/v1/auth/medicalcentre/login
Content-Type: application/json

{
  "email": "clinic@example.com",
  "password": "ClinicSecurePass123"
}

### Add Medical Centre
POST http://localhost:3000/api/v1/medical/addmedicalcentre
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "medicalcentre_name": "Green Valley Hospital",
  "registration_number": "GVH123456",
  "mobile_no": "9998887770",
  "email": "greenvalley@example.com",
  "address_line": "123 Health Street",
  "area": "Sector 15",
  "district": "Lucknow",
  "state": "Uttar Pradesh",
  "pincode": "226010"
}

### Verify Medical Centre
POST http://localhost:3000/api/v1/medical/verifycentres/:medicalCentreId
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "is_verified": true
}

### Fetch all medical centres by superadmin (with token)
POST http://localhost:3000/api/v1/medical/getallmedicalcentres?page=1&limit=10
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

### Get Nearest Medical Centres (within 100 km) USER
POST http://localhost:3000/api/v1/medical/getnearestmedicalcentres?page=1&limit=10&search=anu
Authorization: Bearer <your_user_token>
Content-Type: application/json

{
  "latitude": 22.5731358,
  "longitude": 88.4343624,
  "radius": 100
}

### delete medical centre
POST http://localhost:3000/api/v1/medical/deletemedicalcentre/:id
Authorization: Bearer <your_superadmin_token>

### ADD test to catalouge
POST http://localhost:3000/api/v1/medical/addtesttocatalogue
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "test_name": "Ultrasound Abdomen",
  "type_of_test": "Imaging",
  "components": ["Liver", "Gallbladder", "Pancreas", "Kidneys", "Spleen"],
  "special_requirements":"only drink water before the test"
}

### Add Test to Centre
POST http://localhost:3000/api/v1/medical/tests/assign
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "test_id": "2b2b13aa-c85e-433e-bd3b-1171f33a538d",
  "medicalcentre_id": "MC-1748503434482",
  "price": 450
}


### Get Tests for Medical Centre (with pagination, filter & search) USER
POST http://localhost:3000/api/v1/medical/tests/centre/:medicalcentre_id?page=1&limit=10&type_of_test=Blood&search=liver
Authorization: Bearer <your_user_token>
Content-Type: application/json

# Replace {{medicalcentre_id}} with actual medical centre id


### Get Medical Centre Details with Test Summary
POST http://localhost:3000/api/v1/medical/details/:medicalcentre_id
Authorization: Bearer <your_user_token>


### Get Tests for Medical Centre (with pagination, filter & search) superadmin
POST http://localhost:3000/api/v1/medical/superadmin/tests/centre/:medicalcentre_id?page=1&limit=10&type_of_test=Blood&search=liver
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

# Replace {{medicalcentre_id}} with actual medical centre id


### Get Medical Centre Details with Test Summary superadmin
POST http://localhost:3000/api/v1/medical/superadmin/details/:medicalcentre_id
Authorization: Bearer <your_superadmin_token>



### Combine filters and pagination fetch test catalouge
POST http://localhost:3000/api/v1/medical/tests_catalouge?page=1&limit=10&type_of_test=Imaging&search=ultra
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json


### Update only test catalouge
POST http://localhost:3000/api/v1/medical/update_tests_catalouge/:test_id
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

{
  "test_name":"Ultrasound Abdomen image",
  "special_requirements":"only drink water before the test"
}

### Delete a test catalog
POST http://localhost:3000/api/v1/medical/delete_tests_catalouge/:test_id
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

### Delete test from centre
POST http://localhost:3000/api/v1/medical/medical-centre/:medicalcentre_id/deletetest/:test_id
Authorization: Bearer <your_superadmin_token>
Content-Type: application/json

### Get All Patients
POST http://localhost:3000/api/v1/user/getallpatients
Authorization: Bearer <your_user_token>

### Add a Patient
POST http://localhost:3000/api/v1/user/addpaitents
Content-Type: application/json
Authorization: Bearer <your_user_token>

{
  "full_name": "Amit Sharma",
  "gender": "Male",
  "dob": "1995-06-15",
  "relation": "Brother"
}
Content-Type: multipart/form-data; 

Content-Disposition: form-data; name="prescription"; filename="prescription.pdf"
Content-Type: application/pdf

### add address
POST http://localhost:3000/api/v1/user/postaddress
Content-Type: application/json
Authorization: Bearer <your_user_token>

{
  "label": "Home",
  "address_line": "1234 Main St, Apt 101",
  "area": "Downtown",
  "city": "Mumbai",
  "district": "Mumbai Suburban",
  "state": "Maharashtra",
  "pincode": "400001",
  "landmark": "Near City Mall",
  "contact_number": "+919876543210",
  "latitude": 19.0760,
  "longitude": 72.8777
}

### Get all addresses for the authenticated user
POST http://localhost:3000/api/v1/user/getalladdresses
Authorization: Bearer <your_user_token>

POST http://localhost:3000/api/v1/user/getbookingsummary
Content-Type: application/json
Authorization: Bearer <your_user_token>
{
  "tests": [
    { "medical_test_id": "c97787d1-76eb-4e2a-9f62-dd2da2388de2" },
    { "medical_test_id": "3b6c2383-30c7-4c82-8a76-b2bb3f5a1b31" }
  ]
}

### add booking route for user
POST http://localhost:3000/api/v1/user/addbooking
Content-Type: application/json
Authorization: Bearer <your_user_token>

{
  "patient_id": "d9f070bb-f116-4a4e-b931-b85db08a51fb",
  "address_id": "4d06eec4-7222-4535-806a-fd22091651e4",
  "scheduled_date": "2025-06-15T10:30:00",
  "payment_mode": "UPI",
  "transaction_id": "txn09876",
  "tests": [
    { "medical_test_id": "c97787d1-76eb-4e2a-9f62-dd2da2388de2"},
    { "medical_test_id": "3b6c2383-30c7-4c82-8a76-b2bb3f5a1b31" }
  ]
}

### all orders details for user
POST http://localhost:3000/api/v1/user/allorders
Content-Type: application/json
Authorization: Bearer <your_user_token>


### Upload prescription for a patient
POST http://localhost:3000/api/v1/user/addprescription/:patient_id
Authorization: Bearer <your_user_token>
Content-Type: multipart/form-data; 

Content-Disposition: form-data; name="prescription"; filename="prescription.pdf"
Content-Type: application/pdf


POST http://localhost:3000/api/v1/medical/updatemedicalcentre/:medicalcentre_id
Content-Type: multipart/form-data

Form fields:
- medicalcentre_name: Green Valley Hospital (Updated)
- mobile_no: 8888777700
- logo: (file)
